[package]
name = "compiler"
version = "0.1.0"
authors = ["PJB3005 <pieterjan.briers+git@gmail.com>"]
edition = "2018"

[dependencies]
dreammaker = { git = "https://github.com/SpaceManiac/SpacemanDMM.git" }
#bitflags = "1.0"
structopt = "0.2"
tempfile = "3"